test 14
Signed-off-by: QuikAppTech <110347968+QuikAppTech@users.noreply.github.com>

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -234,21 +234,29 @@ definitions:
         name: Building App with Feature Flags
         script: |
           echo "✅ Start Building APK..."
-#          flutter clean
-#          flutter pub get
+
           flutter build apk --release \
-            --dart-define=WEB_URL="$WEB_URL" \
-            --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY" \
-            --dart-define=IS_CAMERA="$IS_CAMERA" \
-            --dart-define=IS_LOCATION="$IS_LOCATION" \
-            --dart-define=IS_MIC="$IS_MIC" \
-            --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION" \
-            --dart-define=IS_CONTACT="$IS_CONTACT" \
-            --dart-define=IS_SMS="$IS_SMS" \
-            --dart-define=IS_PHONE="$IS_PHONE" \
-            --dart-define=IS_BLUETOOTH="$IS_BLUETOOTH" \
-            > flutter_build.log
-          echo "✅ Build APK Completed"
+          --dart-define=WEB_URL="$WEB_URL" \
+          --dart-define=PUSH_NOTIFY="$PUSH_NOTIFY" \
+          --dart-define=IS_CAMERA="$IS_CAMERA" \
+          --dart-define=IS_LOCATION="$IS_LOCATION" \
+          --dart-define=IS_MIC="$IS_MIC" \
+          --dart-define=IS_NOTIFICATION="$IS_NOTIFICATION" \
+          --dart-define=IS_CONTACT="$IS_CONTACT" \
+          --dart-define=IS_SMS="$IS_SMS" \
+          --dart-define=IS_PHONE="$IS_PHONE" \
+          --dart-define=IS_BLUETOOTH="$IS_BLUETOOTH" \
+          --verbose > flutter_build.log 2>&1
+      
+          echo "✅ Flutter build command completed."
+      
+          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
+          echo "❌ APK not found! Check flutter_build.log for errors."
+          cat flutter_build.log | tail -n 100
+          exit 1
+          fi
+
+          echo "✅ APK successfully built."
 
     - &get_logo
       name: Get logo image from logoUrl
